### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by radare** [xplico/xplico#6]
```
tcp_garbage.c
tcp_garbage.c:119:8: error: unknown type name 'ndpi_protocol'
 static ndpi_protocol nDPIPacket(packet *pkt, struct ndpi_flow_struct *l7flow, struct ndpi_id_struct *l7src, struct ndpi_id_struct *l7dst, bool ipv4)
        ^
tcp_garbage.c: In function 'nDPIPacket':
tcp_garbage.c:126:5: error: unknown type name 'ndpi_protocol'
     ndpi_protocol l7prot_id;
     ^
tcp_garbage.c: In function 'TcpGrbDissector':
tcp_garbage.c:531:5: error: unknown type name 'ndpi_protocol'
     ndpi_protocol l7prot_id;
     ^
tcp_garbage.c:689:64: error: request for member 'master_protocol' in something not a structure or union
             if (stage != 4 && (l7prot_type == NULL || l7prot_id.master_protocol == NDPI_PROTOCOL_HTTP) && l7flow != NULL) {
                                                                ^
tcp_garbage.c:696:30: error: request for member 'protocol' in something not a structure or union
                 if (l7prot_id.protocol != NDPI_PROTOCOL_UNKNOWN) {
                              ^
tcp_garbage.c:698:21: warning: implicit declaration of function 'ndpi_protocol2name' [-Wimplicit-function-declaration]
                     l7prot_type = ndpi_protocol2name(ndpi, l7prot_id, buff, TCP_CFG_LINE_MAX_SIZE);
                     ^
tcp_garbage.c:698:33: warning: assignment makes pointer from integer without a cast
                     l7prot_type = ndpi_protocol2name(ndpi, l7prot_id, buff, TCP_CFG_LINE_MAX_SIZE);
                                 ^
<builtin>: recipe for target 'tcp_garbage.o' failed
```

after fixing those i have other similar errors in udp, ... im using ndpi 1.6.1... but i discovered that there's ndpi 1.7 outside github but after installing it i still get the same errors

**Comment by radare** [comment]
Nevermind :) it builds fine with ndpi 1.7... so there must be a check for dependencies like json-c, ndpi-1.7, and make the pgsql/mysql dependencies optional.

**Comment by radare** [comment]
(and python3)

**Comment by ashirel** [comment]
i'm getting the same error.
i started off with git clone https://github.com/ntop/nDPI.git
how do i know what version it gave me? v2.0 is our for a while . was this problem solved in 1.7 but returned in subsequent  versions?
tnx
ams
